name: Compilar APK FlacConverter

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permiso al Gradlew
      # Entramos a la carpeta exacta que subiste
      run: chmod +x ./FlacConverter/gradlew 

    - name: Compilar APK de Debug
      # Ejecutamos la compilación dentro de tu carpeta
      run: cd FlacConverter && ./gradlew assembleDebug

    - name: Subir APK
      uses: actions/upload-artifact@v4
      with:
        name: FlacConverter-Debug
        # Ruta donde Gradle deja el archivo después de compilar
        path: FlacConverter/app/build/outputs/apk/debug/app-debug.apk
